/**
 * Export configuration and types for PDF/Excel generation
 */

export interface ExportConfig {
  includeSummary: boolean;
  includeRentSchedule: boolean;
  includeCashflow: boolean;
  includeMetrics: boolean;
  includeCharts: boolean;
  includeNotes: boolean;
  branding?: BrandingConfig;
  format?: 'letter' | 'a4' | 'legal';
  orientation?: 'portrait' | 'landscape';
}

export interface BrandingConfig {
  companyName?: string;
  logo?: string; // base64 or URL
  primaryColor?: string;
  secondaryColor?: string;
  footer?: string;
}

export interface ExportMetadata {
  title: string;
  author?: string;
  subject?: string;
  keywords?: string[];
  createdDate: Date;
}

export const DEFAULT_EXPORT_CONFIG: ExportConfig = {
  includeSummary: true,
  includeRentSchedule: true,
  includeCashflow: true,
  includeMetrics: true,
  includeCharts: true,
  includeNotes: true,
  format: 'letter',
  orientation: 'portrait',
};

export const DEFAULT_BRANDING: BrandingConfig = {
  companyName: 'Lease Analyzer',
  primaryColor: '#2563eb',
  secondaryColor: '#64748b',
  footer: 'Generated by B² (Bsquared)',
};

